// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmryy6YQ2DZy8IpularJUJRhDYEeE9qgU',
    appId: '1:797872319437:web:65657abc7b4b7af6547284',
    messagingSenderId: '797872319437',
    projectId: 'projet-web-c1561',
    authDomain: 'projet-web-c1561.firebaseapp.com',
    storageBucket: 'projet-web-c1561.firebasestorage.app',
    measurementId: 'G-86BL8FY3VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoocIkhDYU11fKwELh4aKTqdUme5hguT0',
    appId: '1:797872319437:android:9a652d009e7b91fb547284',
    messagingSenderId: '797872319437',
    projectId: 'projet-web-c1561',
    storageBucket: 'projet-web-c1561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY6shnDwVJbwL-zyytMfc6Fyiy1q-D4ww',
    appId: '1:797872319437:ios:e71072666d9387a5547284',
    messagingSenderId: '797872319437',
    projectId: 'projet-web-c1561',
    storageBucket: 'projet-web-c1561.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY6shnDwVJbwL-zyytMfc6Fyiy1q-D4ww',
    appId: '1:797872319437:ios:e71072666d9387a5547284',
    messagingSenderId: '797872319437',
    projectId: 'projet-web-c1561',
    storageBucket: 'projet-web-c1561.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmryy6YQ2DZy8IpularJUJRhDYEeE9qgU',
    appId: '1:797872319437:web:65657abc7b4b7af6547284',
    messagingSenderId: '797872319437',
    projectId: 'projet-web-c1561',
    authDomain: 'projet-web-c1561.firebaseapp.com',
    storageBucket: 'projet-web-c1561.firebasestorage.app',
    measurementId: 'G-86BL8FY3VD',
  );
}
