services:
  angular-app:
    build:
      context: .
      dockerfile: ./apps/angular-app/Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped

  flutter-app:
    build:
      context: ./apps/flutter-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
